### ISSUE TITLE
O refresh do money top não está feito em async

### ISSUE THREAD

**Issue by jose-manuel-silva** [SrEdition/Solary-Economy#1]
Na classe RefreshMoneyTop, o plugin está a puxar da database os players, em sync, fazendo com que se a conexão da database for lenta ou a quantidade de dados for muita, irá causar um lagspike no servidor (no meu esta causando, lagspikes de 1s e meio), por favor, façam o refresh async para não causar problemas desses.

**Comment by Lucasmellof** [comment]
Estou tendo o mesmo problema em meu servidor, recebo notificação de outros plugins avisando que o SolaryEconomy está criando uma conexão de socket na thread principal. Sugiro usar cache para solucionar o problema e/ou mudar a conexão para assíncrona. Vou fazer um fork do projeto e tentar implementar essas sugestão que eu dei.

**Comment by sredition** [comment]
Peço desculpas pela demora na resposta, o problema foi corrigido.
